#!/usr/bin/env node

'use strict';

const spawn = require('child_process').spawn;

process.env.NODE_ENV = 'test';

const app = spawn('node', ['app', '-e', 'test', '-w', '2'], { stdio: 'inherit' });

app.on('SIGINT', process.exit);
app.on('SIGTERM', process.exit);
app.on('exit', process.exit);

setTimeout(() => {
  const mocha = spawn('mocha', ['-R', 'spec'], { stdio: 'inherit' });
  mocha.on('SIGINT', process.exit);
  mocha.on('SIGTERM', process.exit);
  mocha.on('exit', process.exit);
}, 1000);
