#!/usr/bin/env node

'use strict';

const config = require('../config');
const knex = require('knex');

// This is all a terrible hack until Knex accepts my pull request to support
// database urls without passwords.
let dblessConn;
let dbName;
if (typeof config.knex.connection === "string") {
  const segments = config.knex.connection.split('/');
  dbName = segments[3];
  dblessConn = `${segments.slice(0, 3).join('/')}/`;
} else {
  dbName = config.knex.connection.database;
  dblessConn = { user: config.knex.connection.user };
}


knex({ client: 'mysql', connection: dblessConn })
    .raw(`create database ${dbName}`)
    .then(() => {
      console.log(`${dbName} database created succesfully`);
      process.exit();
    }).catch((e) => {
      if (e && e.code === 'ER_DB_CREATE_EXISTS') {
        console.log(`${dbName} already exists`);
        process.exit();
      }
      console.error('There was an error creating this database:');
      console.error(e);
      process.exit(1);
    });
